name: MinigameLib
version: '0.1.0'
main: com.talexck.minigamelib.MinigameLibPlugin
api-version: '1.21'
description: A Paper 1.21.11 minigame library plugin.
authors:
  - TalexCK
depend:
  - TAB
  - DecentHolograms
